lb:
  image: asteris/haproxy-consul:latest
  environment:
    HAPROXY_DOMAIN: "${IPADDRESS}.xip.io"
    CONSUL_CONNECT: consul:8500
    SERVICE_80_IGNORE: 'yes'
    SERVICE_8080_NAME: 'proxy-admin'
  ports:
    - "80:80"
    - "8080"
  links:
    - "consul"
  volumes:
    - "${PWD}/haproxy.tmpl:/consul-template/template.d/consul.tmpl"

consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  environment:
    SERVICE_IGNORE: 'yes'
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

registrator:
  command: "-ip ${IPADDRESS} consul://consul:8500"
  image: gliderlabs/registrator:latest
  links:
    - "consul"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

web:
  image: tutum/hello-world
  environment:
    SERVICE_NAME: 'web'
  ports:
    - "80"
