lb:
  net: host
  image: asteris/haproxy-consul:latest
  environment:
    HAPROXY_DOMAIN: 10.26.10.92.xip.io
    CONSUL_CONNECT: localhost:8500
  ports:
    - "80:80"

consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

registrator:
  net: host
  command: consul://localhost:8500 -internal
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

web:
  image: httpd:2.4
  volumes:
    - "/home/rpinson/bas/consul/htdocs:/usr/local/apache2/htdocs"
  ports:
    - "80"
