lb:
  net: host
  image: asteris/haproxy-consul:latest
  environment:
    HAPROXY_DOMAIN: "${IPADDRESS}.xip.io"
    CONSUL_CONNECT: localhost:8500
    SERVICE_IGNORE: 'yes'
  ports:
    - "80:80"
  volumes:
    - "${PWD}/haproxy.tmpl:/consul-template/template.d/consul.tmpl"

consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  environment:
    SERVICE_IGNORE: 'yes'
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

registrator:
  net: host
  command: "consul://localhost:8500 -ip ${IPADDRESS}"
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

web:
  image: tutum/hello-world
  environment:
    SERVICE_NAME: 'web'
  ports:
    - "80"
